config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }
  devise_scope :user do
    get '/signup', to: 'users/registrations#new'
    post '/signup', to: 'users/registrations#create'
    get '/login', to: 'users/sessions#new'
    post '/login', to: 'users/sessions#create'
    delete '/logout', to: 'users/sessions#destroy'
  end
  resources :users, only: [:show, :index] do
    member do
      delete 'user_destroy', to: 'users#user_destroy'
    end
  end
  resources :topics do
    resources :comments
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  # モデルの関連定義
  belongs_to :user
  belongs_to :topic
  # バリデーション
  validates :content, presence: true, length: { maximum: 500 }
  validates :user_id, presence: true
  validates :topic_id, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_comment_user, only: [:destroy]

  def create
    @topic = Topic.find(params[:topic_id])
    @comment = @topic.comments.build(comment_params)
    @comment.user = current_user
    if @comment.save
      respond_to do |format|
        format.html { redirect_to @topic }
        format.js
      end
    else
      flash[:danger] = '新しいコメントの投稿に失敗しました。'
      redirect_to root_path
    end
  end

  def destroy
    @topic = Topic.find(params[:topic_id])
    @comment = Comment.find(params[:id])
    if @comment.destroy
      respond_to do |format|
        format.html { redirect_to @topic }
        format.js
      end
    else
      flash[:danger] = 'コメントの削除に失敗しました。'
      redirect_to root_path
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def correct_comment_user
    @comment = current_user.comments.find_by(id: params[:id])
    redirect_to root_path if @comment.nil?
  end
end

app/views/comments/_comment_form.html.erb
<%= form_with(model: [topic, comment]) do |f| %>
  <span class="field">
    <%= f.text_area :content, placeholder: "コメントする", class: 'form-control comment-text-area' %>
  </span>
  <div class="actions">
    <%= f.submit "投稿", class: 'btn' %>
  </div>
<% end %>

app/views/comments/_comment_index.html.erb
<% comments.each.with_index(1) do |comment, i| %>
  <div class="comment">
    <% unless comment.id.nil? %>
      <div class="v">
        <span class="comment-user">
          <%= i %>.
          <%= link_to user_path(comment.user.id) do %>
            <%= comment.user.name %>
          <% end %>
        </span>
        <span class="comment-time">
          <%= comment.created_at.strftime("%Y年%m月%d日%H:%M") %>
        </span>
      </div>
      <p class="comment-content"><%= comment.content %></p>
      <% if current_user?(comment.user) %>
        <span class="comment-delete">
          <%= link_to topic_comment_path(comment.topic_id, comment.id), method: :delete, data: { confirm: "本当に削除しますか？" }, remote: true do %>
            <i class="far fa-trash-alt"></i>削除
          <% end %>
        </span>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/comments/comment_index.js.erb
$("#comment-index").html("<%= escape_javascript(render('comments/comment_index', comments: @comment.topic.comments)) %>");
$("textarea").val('');

app/views/comments/create.js.erb
$("#comment-index").html("<%= escape_javascript(render('comments/comment_index', comments: @comment.topic.comments)) %>");
$("textarea").val('');

app/views/comments/destroy.js.erb
$("#comment-index").html("<%= escape_javascript(render('comments/comment_index', comments: @comment.topic.comments)) %>");
$("textarea").val('');