config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }
  devise_scope :user do
    get '/signup', to: 'users/registrations#new'
    post '/signup', to: 'users/registrations#create'
    get '/login', to: 'users/sessions#new'
    post '/login', to: 'users/sessions#create'
    delete '/logout', to: 'users/sessions#destroy'
  end
  resources :users, only: [:show, :index] do
    member do
      delete 'user_destroy', to: 'users#user_destroy'
    end
  end
  resources :topics do
    resources :comments
  end
end

app/models/topic.rb
class Topic < ApplicationRecord
  # モデルの関連定義
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :topic_categories, dependent: :destroy
  has_many :categories, through: :topic_categories
  # バリデーション
  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 100 }
  validates :description, length: { maximum: 200 }

  default_scope -> { order(updated_at: :desc) }
  scope :from_category, -> (category_id) { where(id: TopicCategory.where(category_id: category_id).select(:topic_id)) }

  # カテゴリー更新処理
  def save_categories(categories)
    current_categories = self.categories.pluck(:category_name) unless self.categories.nil?
    old_categories = current_categories - categories
    new_categories = categories - current_categories

    old_categories.each do |old_name|
      self.categories.delete Category.find_by(category_name: old_name)
    end

    new_categories.each do |new_name|
      topic_category = Category.find_or_create_by(category_name: new_name)
      self.categories << topic_category
    end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :new, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :set_available_categories, only: [:edit, :new]

  def index
    if params[:category_id]
      @selected_category = Category.find(params[:category_id])
      @topics = Topic.from_category(params[:category_id]).
        includes([:categories, :topic_categories]).
        page(params[:page]).
        per(MAX_OF_DISPLAY)
    elsif params[:q]
      @topics = @search.result.includes([:categories, :topic_categories]).page(params[:page]).per(MAX_OF_DISPLAY)
      @search_word = params[:q][:title_or_description_or_comments_content_cont]
    else
      @topics = Topic.includes([:categories, :topic_categories]).page(params[:page]).per(MAX_OF_DISPLAY)
    end
    @categories = Category.all
  end

  def show
    @topic = Topic.find(params[:id])
    @comment = Comment.new
    @comments = @topic.comments.includes([:user]).page(params[:page]).per(MAX_OF_DISPLAY)
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = current_user.topics.build(topic_params)
    category_list = params[:category_list].split(",")
    if @topic.save
      @topic.save_categories(category_list)
      flash[:success] = '新しいトピックが登録されました!'
      redirect_to topic_path(@topic.id)
    else
      flash[:danger] = '新しいトピックの登録に失敗しました。'
      render 'new'
    end
  end

  def edit
    @topic = Topic.find(params[:id])
    @category_list = @topic.categories.pluck(:category_name).join(",")
  end

  def update
    @topic = Topic.find(params[:id])
    category_list = params[:category_list].split(",")
    if @topic.update_attributes(topic_params)
      @topic.save_categories(category_list)
      flash[:success] = "トピックが更新されました！"
      redirect_to topic_path(@topic.id)
    else
      render 'topics/edit'
    end
  end

  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy
    flash[:success] = 'トピックが削除されました。'
    redirect_to current_user
  end

  private

  def topic_params
    params.require(:topic).permit(:title, :description)
  end

  def correct_user
    @topic = Topic.find(params[:id])
    unless current_user.admin? || @topic.user == current_user
      flash[:danger] = "このトピックは編集・削除できません"
      redirect_to root_path
    end
  end

  def set_available_categories
    @all_category_list = Category.all.pluck(:category_name)
  end
end

app/views/topics/_topic.html.erb
<li id="topic-<%= topic.id %>" class="topic-wrap">
  <%= link_to topic do %>
    <div class="topic-title">
      <%= topic.title %>
    </div>
    <div class="topic-time">
      <%= topic.updated_at.strftime("%Y年%m月%d日%H:%M") %>
    </div>
    <div class="topic-description">
      <%= truncate(topic.description, length: 100, omission: ".....") %>
    </div>
    <div class="topic-bottom">
      <div class="topic-category">
        <ul>
          <% topic.categories.each do |category| %>
            <li>
              <%= link_to category.category_name, topics_path(category_id: category.id) %>
            </li>
          <% end %>
        </ul>
      </div>
      <div class="topic-count">
        <i class="fas fa-comment"></i><%= topic.comments.count %>
      </div>
    </div>
  <% end %>
</li>

app/views/topics/edit.html.erb
<% provide(:title, "トピック編集") %>
<div class="container">
  <h2 class="page-tit">トピック編集</h2>
  <div class="topic-form">
    <%= form_for(@topic) do |f|%>
      <div class="field topic-form-tit">
        <%= f.text_field :title, placeholder: "タイトル【必須】", class: 'form-wide form-control form-high' %>
      </div>
      <div class="topic-form-categories">
        <%= f.label "カテゴリー" %>
        <ul id="topic-categories">
        </ul>
        <%= hidden_field_tag :category_hidden, @category_list %>
      </div>
      <div class="field">
        <%= f.text_area :description, placeholder: "トピック概要説明", class: 'form-wide form-control form-high' %>
      </div>
      <div class="actions">
        <%= f.submit "更新する", class: 'btn' %>
      </div>
    <% end %>
  </div>
</div>

<%= javascript_tag do %>
var Topic = {
  all_category_list: <%= raw @all_category_list %>
};
<% end %>

app/views/topics/index.html.erb
<% if @selected_category.present? %>
  <% provide(:title, @selected_category.category_name ) %>
<% else %>
  <% provide(:title, 'トピック一覧') %>
<% end %>
<div class="container">
  <div class="row">
    <h2 class="page-tit">
      <% if @selected_category.present? %>
        <p>トピック一覧</p>
        <%= "カテゴリー：#{@selected_category.category_name}" %>
      <% elsif @search_word.present? %> 
        <p>トピック一覧</p>
        <%= "検索：#{@search_word}" %>
      <% else %>
        <p>トピック一覧</p>
      <% end %>
    </h2>
    <div class="col-md-8 topic-area">
      <ol class="topics">
        <%= render @topics %>
      </ol>
      <div class="paginate-area">
        <%= paginate @topics %>
      </div>
    </div>
    <div class="col-md-4">
      <%= render "shared/category_index", categories: @categories %>
    </div>
  </div>
</div>

app/views/topics/new.html.erb
<% provide(:title, "新規トピック作成") %>
<div class="container">
  <h2 class="page-tit">新規トピック作成</h2>
  <div class="topic-form">
    <%= form_for(@topic) do |f|%>
      <div class="field topic-form-tit">
        <%= f.text_field :title, placeholder: "タイトル【必須】", class: 'form-wide form-control form-high' %>
      </div>
      <div class="field topic-form-categories">
        <%= f.label "カテゴリー" %>
        <ul id="topic-categories">
        </ul>
      </div>
      <div class="field">
        <%= f.text_area :description, placeholder: "トピック概要説明", class: 'form-wide form-control form-high' %>
      </div>
      <div class="actions">
        <%= f.submit "作成する", class: 'btn' %>
      </div>
    <% end %>
  </div>
</div>

<%= javascript_tag do %>
var Topic = {
  all_category_list: <%= raw @all_category_list %>
};
<% end %>

app/views/topics/show.html.erb
<% provide(:title, @topic.title) %>
<div class="container">
  <div class="topic-show-head">
    <h2 class="page-tit topic-show-tit"><%= @topic.title %></h2>
    <div class="topic-show-time">
      <%= @topic.updated_at.strftime("%Y年%m月%d日%H:%M") %>
    </div>
    <div class="topic-show-description">
       <%= @topic.description %>
    </div>
    <div class="topic-show-user">
      <%= link_to user_path(@topic.user) do %>
        <%= @topic.user.name %>
      <% end %>
    </div>
    <div class="topic-show-category">
      <ul>
        <% @topic.categories.each do |category| %>
          <li>
            <%= link_to category.category_name, topics_path(category_id: category.id) %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
  <% if user_signed_in? %>
    <% if current_user.admin? || current_user?(@topic.user) %>
      <div class="topic-show-edit">
        <span class="topic-edit-btn">
          <%= link_to edit_topic_path(@topic) do %>
            <i class="fas fa-edit"></i>編集
          <% end %>
        </span>
        <span class="topic-edit-btn">
          <%= link_to @topic, method: :delete, data: { confirm: "本当に削除しますか？" } do %>
            <i class="far fa-trash-alt"></i>削除
          <% end %>
        </span>
      </div>
    <% end %>
  <% end %>
  <div class="topic-show-area">
    <% if user_signed_in? %>
      <div class="topic-comment-form">
        <%= render "comments/comment_form", topic: @topic, comment: @comment %>
      </div>
    <% end %>
    <div id="comment-index"　class="topic-comment-show">
      <%= render "comments/comment_index", comments: @comments %>
    </div>
  </div>
</div>