config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }
  devise_scope :user do
    get '/signup', to: 'users/registrations#new'
    post '/signup', to: 'users/registrations#create'
    get '/login', to: 'users/sessions#new'
    post '/login', to: 'users/sessions#create'
    delete '/logout', to: 'users/sessions#destroy'
  end
  resources :users, only: [:show, :index] do
    member do
      delete 'user_destroy', to: 'users#user_destroy'
    end
  end
  resources :topics do
    resources :comments
  end
end

app/views/shared/_category_index.html.erb
<div class="category-area">
  <p>カテゴリー</p>
  <% unless categories.blank? %>
    <ul>
      <% categories.each do |category| %>
        <li>
          <%= link_to topics_path(category_id: category.id) do %>
            - <%= category.category_name %>(<%= category.topics.count %>)
          <% end %>
        </li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/shared/_search_form.html.erb
<li class="search-form mx-auto">
  <%= search_form_for @search, url: topics_path do |f|%>
    <%= f.search_field :title_or_description_or_comments_content_cont, placeholder: "トピック検索", class: "serch-field input-xlarge" %>
    <%= button_tag type: 'submit', class: "search-btn" do%>
      <i class="fas fa-search"></i>
    <% end %>
  <% end %>
</li>

app/views/shared/_user_info.html.erb
<div class="user-area">
  <p>ユーザー情報</p>
  <div class="user-area-info">
    <div class="user-name-area">
      <span>名前：</span>
      <span class="user-name"><%= user.name %></span>
    </div>
    <% if current_user?(user) %>
      <div class="user-edit-area">
        <%= link_to edit_user_registration_path do %>
          <span class="user-edit-btn"><i class="fas fa-cog"></i>プロフィール編集</span>
        <% end %>
      </div>
    <% end %>
    <% if current_user.admin? %>
      <div class="user-index-area">
        <%= link_to users_path do %>
          <span class="user-edit-btn">ユーザー一覧</span>
        <% end %>
      </div>
    <% end %>
  </div>
</div>