config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }
  devise_scope :user do
    get '/signup', to: 'users/registrations#new'
    post '/signup', to: 'users/registrations#create'
    get '/login', to: 'users/sessions#new'
    post '/login', to: 'users/sessions#create'
    delete '/logout', to: 'users/sessions#destroy'
  end
  resources :users, only: [:show, :index] do
    member do
      delete 'user_destroy', to: 'users#user_destroy'
    end
  end
  resources :topics do
    resources :comments
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer navbar-expand-sm">
  <div class="container">
    <div class="copyright">
      <p>© 2020. NoticeBoard All Rights Reserved.</p>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-expand-lg navbar-fixed-top">
  <div class="container">
    <%= link_to "NoticeBoard", root_path, id: "logo" %>
    <%= render "shared/search_form" %>
    <span class="navbar-toggler" data-toggle="collapse" data-target="#Navber" aria-controls="Navber" aria-expanded="false" aria-label="レスポンシブ・ナビゲーションバー">
      <i class="fa fa-bars navbar-toggler-icon hidden-lg hidden-md"></i>
    </span>
    <ul class="nav navbar-nav navbar-right collapse navbar-collapse" id="Navber">
      <% if user_signed_in? %>
        <li>
          <%= link_to new_topic_path do %>
            <i class="fas fa-pencil-alt"></i>トピック作成
          <% end %>
        </li>
        <li>
          <%= link_to user_path(current_user) do %>
            <i class="fas fa-user-circle"></i>マイページ
          <% end %>
        </li>
        <li>
          <%= link_to logout_path, method: :delete do %>
            <i class="fas fa-sign-out-alt"></i>ログアウト
          <% end %>
        </li>
      <% else %>
        <li>
          <%= link_to signup_path do %>
            <i class="fas fa-user-plus"></i>新規登録
          <% end %>
        </li>
        <li>
          <%= link_to login_path do %>
            <i class="fas fa-sign-in-alt"></i>ログイン
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</header>

app/views/layouts/_headtag.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title))%></title>
    <%= render'layouts/headtag' %>
    <%= render'layouts/shim'%>
  </head>
  <body>
    <%= render'layouts/header'%>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    </div>
    <%= yield %>
    <%= render'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>